version: '2'
services:
        mysql:
                image: mysql:5.7
                ports:
                       - "3306:3306"
                hostname: mysql
                expose:
                       - "3306"
                environment:
                        - MYSQL_DATABASE=social
                        - MYSQL_USER=alex
                        - MYSQL_PASSWORD=admin
                        - MYSQL_ROOT_PASSWORD=admin
                        - DB_HOSTNAME=socialdb
                volumes:
                        - social-db:/var/lib/mysql
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
                networks:
                        - code-network

        redis:
                image: redis
                ports:
                        - "6379:6379"
                expose:
                        - "6379"
                volumes:
                        - social-cache:/var/lib/redis
                networks:
                        - code-network

        mongodb:
                image: mongo
                ports:
                        - "27017:27017"
                expose:
                        - "27017"
                networks:
                        - mongo-net

                environment:
                        - MONGO_INITDB_DATABASE=social
                        - MONGO_INITDB_ROOT_USERNAME=admin
                        - MONGO_INITDB_ROOT_PASSWORD=admin
                volumes:
                        - mongo-db:/data/db                

        php:
                build: ./tweet-api/
                volumes:
                        - ./tweet-api:/app
                ports:
                        - "8000:8000"
                command: 'php artisan serve --host=0.0.0.0'
                networks:
                        - mongo-net
                depends_on:
                        - mongodb

                expose:
                        - "8000"


        auth:
                build: ./auth/
                ports:
                        - "4000:4000"
                command: 'node index.js'
                environment:
                        - SECRET_TOKEN=4135aa9dc1b842a653dea846903ddb95bfb8c5a10c504a7fa16e10bc31d1fdf0
                        - REGEN_TOKEN=2facdd25190a9c847cee51d3e329cce9cb9e387b4c143dfde0d97a3ebd0a3da2
                        - PORT=4000
                        - MYSQL_PORT=3096

                expose:
                        - "4000"
                depends_on:
                        - redis
                        - mysql
                networks:
                        - code-network
        frontend:
                build: ./la-sfat/
                command: "npm start"
                ports:
                        - "3000:3000"
                expose:
                        - "3000"
                stdin_open: true


volumes:
        social-db:
                driver: local
        social-cache:
                driver: local
        mongo-db:
                driver: local
networks:
        code-network:
                driver: bridge
        mongo-net:
                driver: bridge
